insert into FORMATEUR_TEST (ID, FIRST_NAME, LAST_NAME) values (1,'MOHAMED','BEN SALAH' );
insert into FORMATEUR_TEST (ID, FIRST_NAME, LAST_NAME) values (2,'ALI','BEN SALAH' );
insert into FORMATEUR_TEST (ID, FIRST_NAME, LAST_NAME) values (3,'SALAH','BEN SALAH' );
insert into FORMATEUR_TEST (ID, FIRST_NAME, LAST_NAME) values (4,'MARIEM','BEN SALAH' );
