insert into FORMATEUR_TEST (ID, FIRST_NAME, LAST_NAME) values (1,'MOHAMED','BEN SALAH' );
insert into FORMATEUR_TEST (ID, FIRST_NAME, LAST_NAME) values (2,'ALI','BEN SALAH' );
insert into FORMATEUR_TEST (ID, FIRST_NAME, LAST_NAME) values (3,'SALAH','BEN SALAH' );
insert into FORMATEUR_TEST (ID, FIRST_NAME, LAST_NAME) values (4,'MARIEM','BEN SALAH' );


insert into FORMATION_TEST (ID, ID_FORMATEUR, CODE, TITRE ) values (1,1,'F100','FORMATION SPRING' );
insert into FORMATION_TEST (ID, ID_FORMATEUR, CODE, TITRE ) values (2,1,'F200','FORMATION JAVA' );
insert into FORMATION_TEST (ID, ID_FORMATEUR, CODE, TITRE ) values (3,2,'F300','FORMATION DEVOPS' );
insert into FORMATION_TEST (ID, ID_FORMATEUR, CODE, TITRE ) values (4,2,'F400','FORMATION TESTING' );
